[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.3
  adafruit/Adafruit MAX31865 library@^1.6.2
build_flags =
  -D FW_NAME=\"pumpengruppe-rs485\"
  -D FW_VERSION=\"0.1.0\"
