[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.3
  adafruit/Adafruit MAX31865 library@^1.6.2
  knolleary/PubSubClient@^2.8
build_flags =
  -D FW_NAME=\"pumpengruppe-rs485\"
  -D FW_VERSION=\"0.3.0-s3\"
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32s3_ota]
extends = env:esp32s3
upload_protocol = espota
upload_port = 10.1.20.189
upload_flags =
  --auth=admin
